exceptions should not be thrown out of a destructor

## Solution 1
Destructors should be self contained, it swallows all the exceptions that it
might throw.

```cpp
Dog::~Dog() {
    try {
        // error prone code
    } catch (...) {

    }
}
```

## Solution 2

move exception prone code to a prepare function
